export const PERMISSIONS = {
  VIEW_DASHBOARD: 'view-dashboard',
  CREATE_AUTHORIZATION: 'create-authorization',
  VIEW_AUTHORIZATION: 'view-authorization',
  UPLOAD_DOCUMENT: 'upload-document',
  REVIEW_CLINICAL: 'review-clinical',
  REQUEST_INFORMATION: 'request-information',
  FINAL_DECISION: 'final-decision',
  MANAGE_POLICY: 'manage-policy',
  VIEW_AUDIT: 'view-audit',
  VIEW_ANALYTICS: 'view-analytics',
  VIEW_PATIENTS: 'view-patients'
};

export const ROLE_PERMISSIONS = {
  doctor: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.CREATE_AUTHORIZATION, PERMISSIONS.VIEW_AUTHORIZATION, PERMISSIONS.UPLOAD_DOCUMENT, PERMISSIONS.VIEW_PATIENTS, 'create', 'patients'],
  nurse: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_AUTHORIZATION, PERMISSIONS.REVIEW_CLINICAL, PERMISSIONS.REQUEST_INFORMATION, PERMISSIONS.VIEW_PATIENTS, 'review', 'queue', 'patients'],
  insurance: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_AUTHORIZATION, PERMISSIONS.REQUEST_INFORMATION, PERMISSIONS.FINAL_DECISION, PERMISSIONS.MANAGE_POLICY, PERMISSIONS.VIEW_AUDIT, PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.VIEW_PATIENTS, 'review', 'queue', 'patients', 'policies', 'analytics', 'audit', 'decision'],
  user: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_AUTHORIZATION]
};
