import { Activity, Bell, ChevronDown, Clock3, ClipboardCheck, FileText, HeartPulse, LayoutDashboard, MoreHorizontal, Plus, Settings, ShieldCheck, UploadCloud, Users } from 'lucide-react';
import { NavLink } from 'react-router-dom';
import { useRole } from '../../context/RoleContext';

export default function Sidebar() {
  const { role, profile, can } = useRole();
  const readonlyWorkspace = [[Users, 'Profile', '/profile', true], [ShieldCheck, 'My Policy', '/my-policy', true], [Activity, 'Diagnosis', '/diagnosis', true], [ClipboardCheck, 'My Request', '/my-request', true], [FileText, 'Decision', '/decision', true], [UploadCloud, 'Documents', '/documents', true], [Clock3, 'Timeline', '/timeline', true]];
  const workspace = (role === 'user' || role === 'readonly') ? readonlyWorkspace : role === 'nurse' ? [[LayoutDashboard, 'Overview', '/dashboard', true], [ClipboardCheck, 'Clinical review queue', '/nurse/review', true], [Users, 'Patients', '/patients', can('patients')]] : role === 'doctor' ? [[LayoutDashboard, 'Dashboard', '/dashboard', true], [FileText, 'Total Requests', '/doctor/requests', true], [Activity, 'Approved Requests', '/doctor/requests/approved', true], [UploadCloud, 'Need More Information', '/doctor/requests/need-information', true], [Users, 'Patients', '/doctor/patients', can('patients')], [Bell, 'Notifications', '/doctor/notifications', true]] : [[LayoutDashboard, 'Overview', '/dashboard', true], [Plus, 'New authorization', '/new-authorization', can('create')], [ClipboardCheck, 'Authorization queue', '/queue', can('queue')], [Users, 'Patients', '/patients', can('patients')]];
  const intelligence = [[ShieldCheck, 'Policies', '/policies', can('policies')], [Activity, 'Analytics', '/analytics', can('analytics')], [Clock3, 'Audit trail', '/audit', can('audit')]];
  const links = (items) => <>{items.filter(item => item[3]).map(([ItemIcon, label, to]) => <NavLink end={to === '/dashboard' || to === '/doctor/requests'} key={to} to={to} className={({isActive}) => `nav-item ${isActive ? 'active' : ''}`}><span className="nav-icon"><ItemIcon size={17}/></span><span>{label}</span>{label === 'Authorization queue' && can('queue') && <em>12</em>}</NavLink>)}</>;
  return <aside className="sidebar sidebar-new"><div className="brand"><span className="brand-mark"><HeartPulse size={20}/></span><span>PROAUTH <b>AI</b></span></div><div className="clinical-station"><div className="station-top"><span className="workspace-dot"></span><small>ACTIVE WORKSPACE</small><ChevronDown size={13}/></div><strong>Clinical command center</strong><div className="station-line">{Array.from({ length: 7 }, (_, i) => <i key={i}/>)}</div></div><nav><p className="nav-label">WORKSPACE</p>{links(workspace)}{role !== 'user' && role !== 'readonly' && <><p className="nav-label intelligence-label">INTELLIGENCE</p>{links(intelligence)}</>}</nav><div className="sidebar-bottom"><div className="workload"><div><small>REVIEW CAPACITY</small><strong>{can('review') ? '12' : '3'} <span>active</span></strong></div><div className="ring"><span>{can('review') ? '68' : '42'}%</span></div></div><a className="nav-item settings-link"><span className="nav-icon"><Settings size={17}/></span>Settings</a><div className="profile"><div className="avatar navy">{profile.initials}</div><div><strong>{profile.name}</strong><small>{profile.detail}</small></div><MoreHorizontal size={17}/></div></div></aside>;
}
