import { useState } from 'react';
import { ArrowUpRight, Check, ChevronRight, CircleHelp, FileText, Search, ShieldCheck, Sparkles, UploadCloud, X } from 'lucide-react';
import AppLayout from '../components/layout/AppLayout';
import { Badge, Card } from '../components/ui';
import { Field, Stepper } from '../components/authorization/FormPrimitives';
import Processing from './Processing';

function PatientStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 1 OF 7</p><h2>Patient information</h2><p>Identify the patient or create a new patient record.</p></div><button className="button compact"><Search size={15}/>Search existing patient</button></div><div className="connected"><Check size={16}/><span><strong>FHIR patient record connected</strong><small>Patient demographics verified from your clinical system</small></span></div><div className="fields"><Field label="Patient ID" placeholder="PAT-009821"/><Field label="Date of birth" placeholder="MM / DD / YYYY"/><Field label="First name" placeholder="Maya"/><Field label="Last name" placeholder="Rodriguez"/><Field label="Age" placeholder="58"/><label className="field"><span>Sex</span><select><option>Female</option><option>Male</option></select></label><Field label="Phone" placeholder="(415) 555-0128"/><Field label="Email" placeholder="maya.rodriguez@example.com" wide/></div></>}
function ClinicalStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 2 OF 7</p><h2>Clinical information</h2><p>Provide the clinical context for this authorization request.</p></div></div><div className="fields"><Field label="Primary diagnosis" placeholder="Knee osteoarthritis"/><Field label="ICD-10 code" placeholder="M17.11"/><Field label="Secondary diagnoses" placeholder="Search and select diagnoses" wide/><Field label="Duration of symptoms" placeholder="e.g. 6 months"/><Field label="Clinical symptoms" placeholder="Pain, limited mobility" wide/></div><label className="field textarea"><span>Clinical justification</span><textarea placeholder="Describe the patient’s condition, prior treatments, and clinical rationale for the requested service…"/></label><div className="ai-note"><Sparkles size={17}/><span><strong>AI-readable clinical summary</strong><small>A concise summary will be generated after submission for your review.</small></span></div></>}
function TreatmentStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 3 OF 7</p><h2>Requested service</h2><p>Tell us what is being requested and where it will be delivered.</p></div></div><div className="choice-row">{['Procedure','Imaging','Medication','Therapy','Specialist service'].map((x,i)=><button className={`choice ${i===1?'chosen':''}`} key={x}>{x}</button>)}</div><div className="fields"><Field label="Requested procedure" placeholder="MRI lower extremity" wide/><Field label="Procedure code / CPT / HCPCS" placeholder="73721"/><Field label="Requested date" placeholder="MM / DD / YYYY"/><label className="field"><span>Urgency</span><select><option>Routine</option><option>Urgent</option><option>Emergency</option></select></label><label className="field"><span>Care setting</span><select><option>Outpatient</option><option>Inpatient</option></select></label></div></>}
function InsuranceStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 4 OF 7</p><h2>Insurance & policy</h2><p>Enter member coverage details. Policy evidence is retrieved only after submission.</p></div></div><div className="fields"><Field label="Insurance provider" placeholder="Meridian Health Plan"/><Field label="Plan name" placeholder="Medicare Advantage Plus"/><Field label="Member ID" placeholder="MHP-8821094"/><Field label="Plan ID" placeholder="MA-2026-CA"/><label className="field"><span>Policy type</span><select><option>Medicare</option><option>Commercial</option></select></label><label className="field"><span>Coverage type</span><select><option>Active</option><option>Unknown</option></select></label></div><div className="policy-wait"><ShieldCheck size={19}/><div><strong>Policy intelligence</strong><span>Waiting for policy retrieval after submission</span></div><Badge>Not evaluated</Badge></div></>}
function DocumentsStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 5 OF 7</p><h2>Supporting documents</h2><p>Upload documentation that supports this request.</p></div></div><div className="uploader"><UploadCloud size={28}/><strong>Drop documents here, or <u>browse files</u></strong><span>PDF, DOCX, PNG, or JPG · Maximum file size 20 MB</span></div><div className="doc-row"><div className="doc-icon"><FileText size={19}/></div><div><strong>Clinical_Notes.pdf</strong><small>Clinical notes · 2.4 MB</small></div><Badge type="green"><Check size={12}/>Uploaded</Badge><button><X size={16}/></button></div><div className="doc-row warn"><div className="doc-icon"><FileText size={19}/></div><div><strong>Previous_Treatment.pdf</strong><small>Treatment records · 1.1 MB</small></div><Badge type="amber">Evidence check pending</Badge><button><X size={16}/></button></div></>}
function ReviewStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 6 OF 7</p><h2>Review request</h2><p>Confirm the details below before submitting for AI triage.</p></div></div>{[['Patient','Maya Rodriguez · 58 years · Female','green'],['Clinical information','Knee osteoarthritis (M17.11)','green'],['Requested service','MRI lower extremity · CPT 73721','green'],['Insurance','Meridian Health Plan · Active coverage','green'],['Documents','2 supporting documents attached','amber']].map(x=><div className="review-row" key={x[0]}><span className={`review-check ${x[2]}`}><Check size={14}/></span><div><strong>{x[0]}</strong><small>{x[1]}</small></div><ChevronRight size={16}/></div>)}</>}
function AsideHelp({step}){return <aside className="aside-help"><Card><div className="help-icon"><CircleHelp size={18}/></div><h3>Request guidance</h3><p>{step===0?'Search to prefill patient details from your connected clinical system.':step===4?'Add clinical notes and prior-treatment records when they support medical necessity.':'Only the information needed for this step is shown. You can edit it before submission.'}</p><a>Learn about authorizations <ArrowUpRight size={13}/></a></Card><div className="privacy"><ShieldCheck size={16}/><span><strong>Protected information</strong><small>Your data is encrypted and access is audited.</small></span></div></aside>}

export default function NewAuthorization(){const [step,setStep]=useState(0);const [submitted,setSubmitted]=useState(false); if(submitted)return <Processing/>; return <AppLayout><div className="page workflow"><div className="crumb">Authorization <ChevronRight size={14}/> <span>New request</span></div><div className="workflow-head"><div><h1>New authorization request</h1><p>Complete the request details. You’ll be able to review everything before it is submitted for AI triage.</p></div><button className="text-button">Save as draft</button></div><Stepper step={step}/><div className="form-layout"><Card className="form-card">{step===0&&<PatientStep/>}{step===1&&<ClinicalStep/>}{step===2&&<TreatmentStep/>}{step===3&&<InsuranceStep/>}{step===4&&<DocumentsStep/>}{step>=5&&<ReviewStep/>}<div className="form-actions"><button className="button" disabled={step===0} onClick={()=>setStep(step-1)}>Back</button>{step<5?<button className="button primary" onClick={()=>setStep(step+1)}>Continue <ChevronRight size={16}/></button>:<button className="button primary" onClick={()=>setSubmitted(true)}><Sparkles size={16}/>Submit for AI triage</button>}</div></Card><AsideHelp step={step}/></div></div></AppLayout>}
