import { useState } from 'react';
import { ChevronDown, ChevronRight, Plus, Search, SlidersHorizontal } from 'lucide-react';
import AppLayout from '../components/layout/AppLayout';
import { Badge, Card } from '../components/ui';
import { useAuth } from '../hooks/useAuth';
import { requests } from '../data/requests';

const queueStatuses = ['All', 'Pending review', 'Evidence needed', 'Approved'];

export default function Queue(){const { role } = useAuth();const [search,setSearch]=useState('');const [statusIndex,setStatusIndex]=useState(0);const [attentionOnly,setAttentionOnly]=useState(false);const status=queueStatuses[statusIndex];const visibleRequests=requests.filter(r=>{const matchesSearch=!search||[r.id,r.patient,r.diagnosis].some(field=>field?.toLowerCase().includes(search.toLowerCase()));const matchesStatus=status==='All'||r.status===status;const matchesAttention=!attentionOnly||r.tone!=='green';return matchesSearch&&matchesStatus&&matchesAttention;});return <AppLayout><div className="page queue"><div className="page-heading"><div><h1>Authorization queue</h1></div>{role !== 'insurance' && <button className="button primary"><Plus size={16}/>New authorization</button>}</div><Card><div className="table-tools"><div className="search small"><Search size={16}/><input placeholder="Search request ID, patient, diagnosis…" value={search} onChange={event=>setSearch(event.target.value)}/></div><button className={`button compact ${attentionOnly?'primary':''}`} type="button" onClick={()=>setAttentionOnly(value=>!value)}><SlidersHorizontal size={15}/>{attentionOnly?'Attention only':'Filters'}</button><button className="button compact" type="button" onClick={()=>setStatusIndex((statusIndex+1)%queueStatuses.length)}>Status: {status} <ChevronDown size={14}/></button></div><div className="request-table"><div className="thead"><span>Request</span><span>Patient & diagnosis</span><span>Requested service</span><span>AI triage</span><span>Status</span><span>Submitted</span><span></span></div>{visibleRequests.map(r=><div className="trow" key={r.id} role="link" tabIndex="0" onClick={() => location.href=`/patients/${r.patientId || r.id}`} onKeyDown={event => event.key === 'Enter' && (location.href=`/patients/${r.patientId || r.id}`)}><strong>{r.id}</strong><div className="patient-cell"><div className={`mini-avatar ${r.tone}`}>{r.initials}</div><span><b>{r.patient}</b><small>{r.diagnosis}</small></span></div><span>{r.service}<small>{r.policy}</small></span><span><Badge type={r.tone}>{r.prediction}</Badge><small>{r.confidence} confidence</small></span><Badge type={r.tone}>{r.status}</Badge><small>{r.date}</small><button className="open" type="button" onClick={event=>{event.stopPropagation();location.href=`/request/${r.id}`}}><ChevronRight size={17}/></button></div>)}{visibleRequests.length===0&&<div className="empty"><Search size={27}/><h3>No matching requests</h3><p>Try a different search term or clear filters.</p></div>}</div></Card></div></AppLayout>}
