import { useState } from 'react';
import { ChevronRight, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import AppLayout from '../components/layout/AppLayout';
import { Badge, Card } from '../components/ui';
import { useAuth } from '../hooks/useAuth';
import { requests } from '../data/requests';

export default function Queue(){const { role } = useAuth();const navigate = useNavigate();const [search,setSearch]=useState('');const [attentionOnly,setAttentionOnly]=useState(false);const visibleRequests=requests.filter(r=>{const matchesSearch=!search||[r.id,r.patient,r.diagnosis].some(field=>field?.toLowerCase().includes(search.toLowerCase()));const matchesPending=r.status!=='Approved';const matchesAttention=!attentionOnly||r.tone!=='green';return matchesSearch&&matchesPending&&matchesAttention;});const viewPatient=r=>navigate(`/patients/${r.patientId || r.id}`);return <AppLayout><div className="page queue"><div className="page-heading"><div><h1>Authorization queue</h1><p>Cases awaiting a final decision.</p></div>{role !== 'insurance' && <button className="button primary"><Plus size={16}/>New authorization</button>}</div><Card><div className="table-tools"><div className="search small"><Search size={16}/><input placeholder="Search request ID, patient, diagnosis…" aria-label="Search request ID, patient, diagnosis" value={search} onChange={event=>setSearch(event.target.value)}/></div><button className={`button compact ${attentionOnly?'primary':''}`} type="button" onClick={()=>setAttentionOnly(value=>!value)}><SlidersHorizontal size={15}/>{attentionOnly?'Attention only':'Filters'}</button></div><div className="request-table"><div className="thead"><span>Request</span><span>Patient & diagnosis</span><span>Requested service</span><span>AI triage</span><span>Status</span><span>Submitted</span><span></span></div>{visibleRequests.map(r=><div className="trow" key={r.id} role="link" tabIndex="0" onClick={() => viewPatient(r)} onKeyDown={event => event.key === 'Enter' && viewPatient(r)}><strong>{r.id}</strong><div className="patient-cell"><div className={`mini-avatar ${r.tone}`}>{r.initials}</div><span><b>{r.patient}</b><small>{r.diagnosis}</small></span></div><span>{r.service}<small>{r.policy}</small></span><span><Badge type={r.tone}>{r.prediction}</Badge><small>{r.confidence} confidence</small></span><Badge type={r.tone}>{r.status}</Badge><small>{r.date}</small><button className="open" type="button" onClick={event=>{event.stopPropagation();viewPatient(r);}}><ChevronRight size={17}/></button></div>)}{visibleRequests.length===0&&<div className="empty"><Search size={27}/><h3>No pending cases</h3><p>Cases awaiting a decision will appear here.</p></div>}</div></Card></div></AppLayout>}
