import { lazy, Suspense, useState } from 'react';
import { Navigate, useParams } from 'react-router-dom';
import { Activity, BarChart3, Check, Clock3, FileText, Search, ShieldCheck } from 'lucide-react';
import AppLayout from '../components/layout/AppLayout';
import { Badge, Card } from '../components/ui';
import { DecisionPipeline, StatCard } from '../components/dashboard/DashboardWidgets';
import { authorizationService } from '../services/authorizationService';
import { policyService } from '../services/policyService';
import { useAuth } from '../hooks/useAuth';

const AnatomyViewer = lazy(() => import('../components/patient/AnatomyViewer'));

export function ReadonlyPolicyPage() {
  const policies = policyService.getReadonlyPolicies();
  const [query, setQuery] = useState('');
  const visiblePolicies = policies.filter(policy => `${policy.type} ${policy.area} ${policy.overview}`.toLowerCase().includes(query.toLowerCase()));
  return <AppLayout><div className="page dashboard"><div className="page-heading"><div><p className="eyebrow">POLICY EXPLORER</p><h1>Policy explorer</h1><p>Search and review policy coverage information available to your account.</p></div></div><div className="search small"><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search policy" aria-label="Search policy"/></div><div className="analytics-grid">{visiblePolicies.map(policy => <Card className="pipeline" key={policy.type}><div className="section-title"><div><p className="eyebrow">{policy.type}</p><h3>{policy.area}</h3></div><Badge type="green">{policy.status}</Badge></div><div className="policy-meta"><span><b>Policy type</b>{policy.type}</span><span><b>Coverage area</b>{policy.area}</span><span><b>Effective date</b>{policy.effective}</span></div><p className="body-copy">{policy.overview}</p><div className="criteria"><span className="dot green"></span><span>Coverage criteria</span><small>{policy.coverage}</small></div><div className="criteria"><span className="dot green"></span><span>Diagnosis criteria</span><small>{policy.diagnosis}</small></div><div className="criteria"><span className="dot blue"></span><span>Procedure criteria</span><small>{policy.procedure}</small></div><div className="criteria"><span className="dot amber"></span><span>Documentation requirements</span><small>{policy.documentation}</small></div><div className="evidence-quote"><span><ShieldCheck size={15}/></span><div><strong>Retrieved evidence</strong><p>{policy.evidence}</p></div></div></Card>)}</div></div></AppLayout>;
}

export function ReadonlyAnalyticsPage() {
  const metrics = authorizationService.getReadonlyAnalytics();
  return <AppLayout><div className="page simple"><p className="eyebrow">READ-ONLY ANALYTICS</p><h1>Authorization analytics</h1><p className="lead">View operational trends without reviewer actions or export controls.</p><div className="stat-grid"><StatCard label="Authorization volume" value={metrics.requestsToday} delta="Requests today" tone="blue" icon={<FileText size={20}/>}/><StatCard label="Approval rate" value="59.4%" delta="76 approved" tone="green" icon={<Check size={20}/>}/><StatCard label="Nurse review rate" value="24.2%" delta="31 requests" tone="blue" icon={<Clock3 size={20}/>}/><StatCard label="More information rate" value="16.4%" delta="21 requests" tone="amber" icon={<Activity size={20}/>}/></div><DecisionPipeline/><div className="analytics-grid"><Card><div className="section-title"><h3>Average processing time</h3><Badge type="blue">4m 12s</Badge></div><p className="body-copy">Average time from request intake to available triage summary.</p></Card><Card><div className="section-title"><h3>Policy distribution</h3><BarChart3 size={18}/></div><div className="criteria"><span>Medicare Advantage</span><Badge type="blue">42%</Badge></div><div className="criteria"><span>Commercial</span><Badge type="green">35%</Badge></div><div className="criteria"><span>Medicaid</span><Badge type="amber">23%</Badge></div></Card><Card><div className="section-title"><h3>Request type distribution</h3></div><div className="criteria"><span>Imaging</span><Badge type="blue">38%</Badge></div><div className="criteria"><span>Medication</span><Badge type="green">34%</Badge></div><div className="criteria"><span>Therapy</span><Badge type="amber">28%</Badge></div></Card><Card><div className="section-title"><h3>AI triage accuracy</h3><Badge type="green">91%</Badge></div><p className="body-copy">Read-only model performance summary.</p></Card><Card><div className="section-title"><h3>Model confidence distribution</h3></div><div className="criteria"><span>High confidence</span><Badge type="green">68%</Badge></div><div className="criteria"><span>Review range</span><Badge type="blue">24%</Badge></div><div className="criteria"><span>Low confidence</span><Badge type="amber">8%</Badge></div></Card><Card><div className="section-title"><h3>Human override rate</h3><Badge type="blue">7.2%</Badge></div><p className="body-copy">Summary only. Reviewer actions are not exposed to this role.</p></Card></div></div></AppLayout>;
}

export function ReadonlyDashboard({ user }) {
  const record = authorizationService.getReadonlySummary(user.id).requests[0];
  return <AppLayout><div className="page simple"><h1>{user.name}</h1><Card><div className="section-title"><div><p className="eyebrow">USER PROFILE</p><h3>{user.name}</h3></div></div><div className="policy-meta"><span><b>Name</b>{user.name}</span><span><b>Email</b>{user.email}</span><span><b>User ID</b>{user.id}</span><span><b>Patient ID</b>{record.patientId}</span><span><b>Member ID</b>{record.memberId}</span><span><b>Age / Sex</b>{record.age} / {record.sex}</span><span><b>Date of birth</b>{record.dateOfBirth}</span><span><b>Plan name</b>{record.planName}</span><span><b>Plan ID</b>{record.planId}</span><span><b>Coverage status</b>{record.coverageStatus}</span></div><div className="criteria"><span className="dot blue"></span><span>Policy</span><small>{record.policyName} · {record.policyId} · {record.policyType} · Effective {record.policyEffective} · {record.coverageStatus}</small></div><div className="criteria"><span className="dot green"></span><span>Diagnosis</span><small>{record.diagnosis} ({record.icd10}) · Secondary: {record.secondaryDiagnoses}</small></div><div className="criteria"><span className="dot green"></span><span>Clinical history</span><small>{record.clinicalHistory}</small></div><div className="criteria"><span className="dot blue"></span><span>Their request</span><small>{record.service} · Code {record.procedureCode} · {record.urgency} · {record.careSetting}</small></div><div className="criteria"><span className="dot amber"></span><span>Status</span><small>{record.status} · Submitted {record.date} · Updated {record.lastUpdated}</small></div><div className="evidence-quote"><span><ShieldCheck size={15}/></span><div><strong>Decision: {record.decision}</strong><p>{record.decisionExplanation}</p>{record.missingInformation && <small>Missing information: {record.missingInformation}</small>}</div></div><div className="criteria"><span className="dot blue"></span><span>Documents</span><small>{record.documents.map(([name, status]) => `${name} (${status})`).join(' · ')}</small></div><div className="criteria"><span className="dot green"></span><span>Timeline</span><small>{record.timeline.join(' → ')}</small></div></Card></div></AppLayout>;
}

export function ReadonlyAuthorizationPage() {
  const { id } = useParams();
  const { user } = useAuth();
  const request = authorizationService.getReadonlyAuthorization(user.id, id);
  if (!request) return <Navigate to="/dashboard" replace/>;
  return <AppLayout><div className="page simple"><p className="eyebrow">READ-ONLY AUTHORIZATION</p><h1>{request.id}</h1><p className="lead">View-only details for your assigned authorization record.</p><Card><div className="section-title"><div><p className="eyebrow">REQUEST STATUS</p><h3>{request.service}</h3></div><Badge type={request.tone}>{request.status}</Badge></div><div><div className="policy-meta"><span><b>Patient</b>{request.patient}</span></div><div className="policy-meta"><span><b>Service</b>{request.service}</span></div><div className="policy-meta"><span><b>Decision</b>{request.decision}</span></div><div className="policy-meta"><span><b>Submitted</b>{request.date}</span></div><div className="policy-meta"><span><b>Last updated</b>{request.lastUpdated}</span></div></div><div className="evidence-quote"><span><ShieldCheck size={15}/></span><div><strong>Why this result</strong><p>{request.decisionExplanation}</p>{request.missingInformation && <small>Missing information: {request.missingInformation}</small>}</div></div></Card></div></AppLayout>;
}

function ReadonlyCategoryPage({ category, title, children }) {
  const { user } = useAuth();
  const record = authorizationService.getReadonlyRecord(user.id);
  return <AppLayout><div className="page dashboard"><div className="page-heading"><div><h1>{title}</h1></div></div><Card className="pipeline readonly-details"><div className="section-title"><div><p className="eyebrow">{category}</p><h3>{user.name}</h3></div></div>{children(record, user)}</Card></div></AppLayout>;
}

export function ReadonlyProfilePage() { return <ReadonlyCategoryPage category="PROFILE" title="Profile">{(record, user) => <div><div className="policy-meta"><span><b>Name</b>{user.name}</span></div><div className="policy-meta"><span><b>Email</b>{user.email}</span></div><div className="policy-meta"><span><b>Patient ID</b>{record?.patientId}</span></div><div className="policy-meta"><span><b>Member ID</b>{record?.memberId}</span></div><div className="policy-meta"><span><b>Age / Sex</b>{record?.age} / {record?.sex}</span></div><div className="policy-meta"><span><b>Date of birth</b>{record?.dateOfBirth}</span></div><div className="policy-meta"><span><b>Insurance plan</b>{record?.planName}</span></div><div className="policy-meta"><span><b>Coverage status</b>{record?.coverageStatus}</span></div></div>}</ReadonlyCategoryPage>; }
export function ReadonlyPolicyCategoryPage() { return <ReadonlyCategoryPage category="MY POLICY" title="My policy">{record => <div><div className="policy-meta"><span><b>Policy name</b>{record?.policyName}</span></div><div className="policy-meta"><span><b>Policy ID</b>{record?.policyId}</span></div><div className="policy-meta"><span><b>Policy type</b>{record?.policyType}</span></div><div className="policy-meta"><span><b>Effective date</b>{record?.policyEffective}</span></div><div className="policy-meta"><span><b>Coverage status</b>{record?.coverageStatus}</span></div></div>}</ReadonlyCategoryPage>; }
export function ReadonlyDiagnosisPage() { return <ReadonlyCategoryPage category="DIAGNOSIS" title="Diagnosis">{record => <><div><div className="policy-meta"><span><b>Primary diagnosis</b>{record?.diagnosis}</span></div><div className="policy-meta"><span><b>ICD-10 code</b>{record?.icd10}</span></div><div className="policy-meta"><span><b>Secondary diagnoses</b>{record?.secondaryDiagnoses}</span></div><div className="policy-meta"><span><b>Relevant clinical history</b>{record?.clinicalHistory}</span></div></div><Suspense fallback={<Card><p className="lead">Loading anatomy context...</p></Card>}><AnatomyViewer diagnosis={record?.diagnosis} icdCode={record?.icd10} procedure={record?.service} status={record?.status}/></Suspense></>}</ReadonlyCategoryPage>; }
export function ReadonlyRequestPage() { return <ReadonlyCategoryPage category="MY REQUEST" title="My request">{record => <div><div className="policy-meta"><span><b>Procedure</b>{record?.service}</span></div><div className="policy-meta"><span><b>Procedure code</b>{record?.procedureCode}</span></div><div className="policy-meta"><span><b>Urgency</b>{record?.urgency}</span></div><div className="policy-meta"><span><b>Care setting</b>{record?.careSetting}</span></div><div className="policy-meta"><span><b>Status</b>{record?.status}</span></div><div className="policy-meta"><span><b>Submitted</b>{record?.date}</span></div><div className="policy-meta"><span><b>Last updated</b>{record?.lastUpdated}</span></div></div>}</ReadonlyCategoryPage>; }
export function ReadonlyDecisionPage() { return <ReadonlyCategoryPage category="DECISION" title="Decision">{record => <><div className="decision-banner"><div><p>DECISION</p><h2>{record?.decision}</h2><span>{record?.status}</span></div></div><div className="evidence-quote"><span><ShieldCheck size={15}/></span><div><strong>Why this result</strong><p>{record?.decisionExplanation}</p>{record?.missingInformation && <small>Missing information: {record.missingInformation}</small>}</div></div></>}</ReadonlyCategoryPage>; }
export function ReadonlyDocumentsPage() { return <ReadonlyCategoryPage category="DOCUMENTS" title="Documents">{record => <div>{record?.documents.map(([name, status]) => <div className="policy-meta" key={name}><span><b>{name}</b>{status}</span></div>)}</div>}</ReadonlyCategoryPage>; }
export function ReadonlyTimelinePage() { return <ReadonlyCategoryPage category="TIMELINE" title="Timeline">{record => <div>{record?.timeline.map((event, index) => <div className="policy-meta" key={event}><span><b>{event}</b>{index === 0 ? record.date : index === 1 ? 'In progress' : record.lastUpdated}</span></div>)}</div>}</ReadonlyCategoryPage>; }
