import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Navigate, useNavigate } from 'react-router-dom';
import { Activity, BrainCircuit, Check, ChevronDown, ChevronRight, CircleHelp, Clock3, FileText, Plus, Search, ShieldCheck, SlidersHorizontal, Sparkles, UploadCloud, Users, X, ArrowUpRight } from 'lucide-react';
import AppLayout from './components/layout/AppLayout';
import { Badge, Card } from './components/ui';
import { RoleProvider, useRole } from './context/RoleContext';
import { AuthProvider, useAuth } from './hooks/useAuth';
import { requests } from './data/requests';
import { DecisionPipeline, StatCard } from './components/dashboard/DashboardWidgets';
import { Field, Stepper } from './components/authorization/FormPrimitives';
import AppRouter from './router/AppRouter';
import RoleDashboard from './components/dashboard/RoleDashboard';
import DoctorRequests from './features/doctor/pages/DoctorRequests';
import DoctorDocuments from './features/doctor/pages/DoctorDocuments';
import DoctorPatientDetail from './features/doctor/pages/DoctorPatientDetail';
import DoctorPatients from './features/doctor/pages/DoctorPatients';
import ReviewerAuthorization from './features/insurance/pages/ReviewerAuthorization';
import ReviewerPatientDetail from './features/insurance/pages/ReviewerPatientDetail';
import ReviewerPatients from './features/insurance/pages/ReviewerPatients';
import NursePatients from './features/nurse/pages/NursePatients';
import NursePatientDetail from './features/nurse/pages/NursePatientDetail';
import { ReadonlyAnalyticsPage, ReadonlyAuthorizationPage, ReadonlyDiagnosisPage, ReadonlyDocumentsPage, ReadonlyPolicyCategoryPage, ReadonlyProfilePage, ReadonlyRequestPage, ReadonlyDecisionPage, ReadonlyTimelinePage, ReadonlyPolicyPage } from './pages/ReadonlyViews';
import ResultPage from './pages/ResultPage';
import './styles.css';
import './access.css';
import './sidebar.css';
import './login.css';
import './readonly.css';
import './layout-consistency.css';

function NewAuthorization(){const [step,setStep]=useState(0);const [submitted,setSubmitted]=useState(false); if(submitted)return <Processing/>; return <AppLayout><div className="page workflow"><div className="crumb">Authorization <ChevronRight size={14}/> <span>New request</span></div><div className="workflow-head"><div><h1>New authorization request</h1><p>Complete the request details. You’ll be able to review everything before it is submitted for AI triage.</p></div><button className="text-button">Save as draft</button></div><Stepper step={step}/><div className="form-layout"><Card className="form-card">{step===0&&<PatientStep/>}{step===1&&<ClinicalStep/>}{step===2&&<TreatmentStep/>}{step===3&&<InsuranceStep/>}{step===4&&<DocumentsStep/>}{step>=5&&<ReviewStep/>}<div className="form-actions"><button className="button" disabled={step===0} onClick={()=>setStep(step-1)}>Back</button>{step<5?<button className="button primary" onClick={()=>setStep(step+1)}>Continue <ChevronRight size={16}/></button>:<button className="button primary" onClick={()=>setSubmitted(true)}><Sparkles size={16}/>Submit for AI triage</button>}</div></Card><AsideHelp step={step}/></div></div></AppLayout>}
function PatientStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 1 OF 7</p><h2>Patient information</h2><p>Identify the patient or create a new patient record.</p></div><button className="button compact"><Search size={15}/>Search existing patient</button></div><div className="connected"><Check size={16}/><span><strong>FHIR patient record connected</strong><small>Patient demographics verified from your clinical system</small></span></div><div className="fields"><Field label="Patient ID" placeholder="PAT-009821"/><Field label="Date of birth" placeholder="MM / DD / YYYY"/><Field label="First name" placeholder="Maya"/><Field label="Last name" placeholder="Rodriguez"/><Field label="Age" placeholder="58"/><label className="field"><span>Sex</span><select><option>Female</option><option>Male</option></select></label><Field label="Phone" placeholder="(415) 555-0128"/><Field label="Email" placeholder="maya.rodriguez@example.com" wide/></div></>}
function ClinicalStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 2 OF 7</p><h2>Clinical information</h2><p>Provide the clinical context for this authorization request.</p></div></div><div className="fields"><Field label="Primary diagnosis" placeholder="Knee osteoarthritis"/><Field label="ICD-10 code" placeholder="M17.11"/><Field label="Secondary diagnoses" placeholder="Search and select diagnoses" wide/><Field label="Duration of symptoms" placeholder="e.g. 6 months"/><Field label="Clinical symptoms" placeholder="Pain, limited mobility" wide/></div><label className="field textarea"><span>Clinical justification</span><textarea placeholder="Describe the patient’s condition, prior treatments, and clinical rationale for the requested service…"/></label><div className="ai-note"><Sparkles size={17}/><span><strong>AI-readable clinical summary</strong><small>A concise summary will be generated after submission for your review.</small></span></div></>}
function TreatmentStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 3 OF 7</p><h2>Requested service</h2><p>Tell us what is being requested and where it will be delivered.</p></div></div><div className="choice-row">{['Procedure','Imaging','Medication','Therapy','Specialist service'].map((x,i)=><button className={`choice ${i===1?'chosen':''}`} key={x}>{x}</button>)}</div><div className="fields"><Field label="Requested procedure" placeholder="MRI lower extremity" wide/><Field label="Procedure code / CPT / HCPCS" placeholder="73721"/><Field label="Requested date" placeholder="MM / DD / YYYY"/><label className="field"><span>Urgency</span><select><option>Routine</option><option>Urgent</option><option>Emergency</option></select></label><label className="field"><span>Care setting</span><select><option>Outpatient</option><option>Inpatient</option></select></label></div></>}
function InsuranceStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 4 OF 7</p><h2>Insurance & policy</h2><p>Enter member coverage details. Policy evidence is retrieved only after submission.</p></div></div><div className="fields"><Field label="Insurance provider" placeholder="Meridian Health Plan"/><Field label="Plan name" placeholder="Medicare Advantage Plus"/><Field label="Member ID" placeholder="MHP-8821094"/><Field label="Plan ID" placeholder="MA-2026-CA"/><label className="field"><span>Policy type</span><select><option>Medicare</option><option>Commercial</option></select></label><label className="field"><span>Coverage type</span><select><option>Active</option><option>Unknown</option></select></label></div><div className="policy-wait"><ShieldCheck size={19}/><div><strong>Policy intelligence</strong><span>Waiting for policy retrieval after submission</span></div><Badge>Not evaluated</Badge></div></>}
function DocumentsStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 5 OF 7</p><h2>Supporting documents</h2><p>Upload documentation that supports this request.</p></div></div><div className="uploader"><UploadCloud size={28}/><strong>Drop documents here, or <u>browse files</u></strong><span>PDF, DOCX, PNG, or JPG · Maximum file size 20 MB</span></div><div className="doc-row"><div className="doc-icon"><FileText size={19}/></div><div><strong>Clinical_Notes.pdf</strong><small>Clinical notes · 2.4 MB</small></div><Badge type="green"><Check size={12}/>Uploaded</Badge><button><X size={16}/></button></div><div className="doc-row warn"><div className="doc-icon"><FileText size={19}/></div><div><strong>Previous_Treatment.pdf</strong><small>Treatment records · 1.1 MB</small></div><Badge type="amber">Evidence check pending</Badge><button><X size={16}/></button></div></>}
function ReviewStep(){return <><div className="form-title"><div><p className="eyebrow">STEP 6 OF 7</p><h2>Review request</h2><p>Confirm the details below before submitting for AI triage.</p></div></div>{[['Patient','Maya Rodriguez · 58 years · Female','green'],['Clinical information','Knee osteoarthritis (M17.11)','green'],['Requested service','MRI lower extremity · CPT 73721','green'],['Insurance','Meridian Health Plan · Active coverage','green'],['Documents','2 supporting documents attached','amber']].map(x=><div className="review-row" key={x[0]}><span className={`review-check ${x[2]}`}><Check size={14}/></span><div><strong>{x[0]}</strong><small>{x[1]}</small></div><ChevronRight size={16}/></div>)}</>}
function AsideHelp({step}){return <aside className="aside-help"><Card><div className="help-icon"><CircleHelp size={18}/></div><h3>Request guidance</h3><p>{step===0?'Search to prefill patient details from your connected clinical system.':step===4?'Add clinical notes and prior-treatment records when they support medical necessity.':'Only the information needed for this step is shown. You can edit it before submission.'}</p><a>Learn about authorizations <ArrowUpRight size={13}/></a></Card><div className="privacy"><ShieldCheck size={16}/><span><strong>Protected information</strong><small>Your data is encrypted and access is audited.</small></span></div></aside>}
function Processing(){const nav=useNavigate(); const [active,setActive]=useState(4); React.useEffect(()=>{let n=4;const t=setInterval(()=>{n++;setActive(n);if(n>6){clearInterval(t);setTimeout(()=>nav('/request/PA-10482'),500)}},700);return()=>clearInterval(t)},[]);const steps=['Request received','Patient context loaded','Applicable policy retrieved','Documents analyzed','Coverage evaluation','ML triage running','Result ready'];return <AppLayout><div className="processing page"><p className="eyebrow">AUTHORIZATION PA-10482</p><h1>Analyzing your request</h1><p className="lead">We’re gathering policy and clinical context to prepare a transparent triage recommendation.</p><Card className="processing-card"><div className="processing-head"><div className="ai-spark"><Sparkles size={22}/></div><div><h3>AI processing</h3><p>High-level activity only — no clinical decisions are made automatically.</p></div><Badge type="blue">In progress</Badge></div><div className="process-list">{steps.map((s,i)=><div className={`process-row ${i===active?'active':''} ${i<active?'complete':''}`} key={s}><span>{i<active?<Check size={15}/>:i===active?<i/>:i+1}</span><strong>{s}</strong><small>{i<active?'Completed':i===active?'Processing…':'Waiting'}</small></div>)}</div></Card><p className="safe-note"><ShieldCheck size={16}/>This is a decision-support workflow. A qualified reviewer retains final authority.</p></div></AppLayout>}

function Queue(){const { role } = useAuth();return <AppLayout><div className="page queue"><div className="page-heading"><div><h1>Authorization queue</h1></div>{role !== 'insurance' && <button className="button primary"><Plus size={16}/>New authorization</button>}</div><Card><div className="table-tools"><div className="search small"><Search size={16}/><input placeholder="Search request ID, patient, diagnosis…"/></div><button className="button compact"><SlidersHorizontal size={15}/>Filters</button><button className="button compact">Status: All <ChevronDown size={14}/></button></div><div className="request-table"><div className="thead"><span>Request</span><span>Patient & diagnosis</span><span>Requested service</span><span>AI triage</span><span>Status</span><span>Submitted</span><span></span></div>{requests.map(r=><div className="trow" key={r.id} role="link" tabIndex="0" onClick={() => location.href=`/patients/${r.patientId || r.id}`} onKeyDown={event => event.key === 'Enter' && (location.href=`/patients/${r.patientId || r.id}`)}><strong>{r.id}</strong><div className="patient-cell"><div className={`mini-avatar ${r.tone}`}>{r.initials}</div><span><b>{r.patient}</b><small>{r.diagnosis}</small></span></div><span>{r.service}<small>{r.policy}</small></span><span><Badge type={r.tone}>{r.prediction}</Badge><small>{r.confidence} confidence</small></span><Badge type={r.tone}>{r.status}</Badge><small>{r.date}</small><button className="open" type="button" onClick={event=>{event.stopPropagation();location.href=`/request/${r.id}`}}><ChevronRight size={17}/></button></div>)}</div></Card></div></AppLayout>}
function SimplePage({title,subtitle,children}){return <AppLayout><div className="page simple"><h1>{title}</h1>{subtitle && <p className="lead">{subtitle}</p>}{children||<Card className="empty"><BrainCircuit size={27}/><h3>No records available</h3><p>Information for this workspace will appear when records are available.</p></Card>}</div></AppLayout>}
function Analytics(){return <SimplePage title="Authorization analytics" subtitle="Operational patterns across your authorization workflow."><div className="analytics-grid"><StatCard label="Approval rate" value="61.8%" delta="+4.2%" tone="green" icon={<Activity/>}/><StatCard label="Avg. processing" value="4m 12s" delta="-38s" tone="blue" icon={<Clock3/>}/><StatCard label="Human override" value="7.2%" delta="Within target" tone="green" icon={<Users/>}/><Card className="chart"><div className="section-title"><h3>Authorization volume</h3><Badge>Last 7 days</Badge></div><div className="bars">{[46,70,55,84,72,96,81].map((x,i)=><div key={i}><i style={{height:x+'%'}}></i><span>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</span></div>)}</div></Card></div></SimplePage>}
function RoleScopedPage({ readonly, standard, doctor, insurance, nurse }){const { role } = useAuth();const insuranceRole = role === 'insurance' || role === 'reviewer';return role === 'user' || role === 'readonly' ? readonly : role === 'doctor' && doctor ? doctor : insuranceRole && insurance ? insurance : role === 'nurse' && nurse ? nurse : standard;}
function Root(){return <AppRouter pages={{dashboard:<RoleScopedPage readonly={<ReadonlyProfilePage/>} standard={<RoleDashboard/>}/>,profile:<ReadonlyProfilePage/>,myPolicy:<ReadonlyPolicyCategoryPage/>,diagnosis:<ReadonlyDiagnosisPage/>,myRequest:<ReadonlyRequestPage/>,decision:<ReadonlyDecisionPage/>,documents:<ReadonlyDocumentsPage/>,doctorDocuments:<DoctorDocuments/>,timeline:<ReadonlyTimelinePage/>,newAuthorization:<NewAuthorization/>,patients:<RoleScopedPage doctor={<DoctorPatients/>} nurse={<NursePatients/>} insurance={<ReviewerPatients/>} standard={<SimplePage title="Patient profiles" subtitle="Your patients and authorization status."/>}/>,patientDetail:<RoleScopedPage doctor={<DoctorPatientDetail/>} nurse={<NursePatientDetail/>} insurance={<ReviewerPatientDetail/>} standard={<SimplePage title="Patient profile" subtitle="Patient authorization details."/>}/>,doctorRequests:<DoctorRequests/>,notifications:<SimplePage title="Notifications"/>,queue:<Queue/>,authorization:<RoleScopedPage readonly={<ReadonlyAuthorizationPage/>} insurance={<ReviewerAuthorization/>} standard={<ResultPage/>}/>,policies:<SimplePage title="Policy explorer" subtitle="Search policies and surface evidence for a clear review experience."/>,analytics:<Analytics/>,audit:<SimplePage title="Audit trail" subtitle="A transparent event record for every authorization."/>}}/>}
createRoot(document.getElementById('root')).render(<AuthProvider><RoleProvider><Root/></RoleProvider></AuthProvider>);
